# Predicting Employees Attrition

In this activity, you will apply your knowledge of deep learning models to predict whether an employee is likely to depart from a company.

## Instructions:

The steps for this activity are broken out into the following sections:

* Preprocess the data.

* Create a neural network model to predict employee attrition.

* Train and evaluate the neural network model.


#### Preprocess the Data 

1. Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

2. Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

3. Create a list of categorical variables.

> **Rewind** The Pandas DataFrame `dtypes` property returns a Pandas Series that displays the data type of each column. The column name is the index. You can create the list of categorical variables manually. Or, you can use Pandas filtering. For more detail about the filtering process, review the [`dtypes` documentation at Pandas API reference](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html).

4. Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

5. Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

> **Note** To complete this step, you will employ the Pandas `concat()` function, which was introduced earlier in the course. Recall that we use the `concat` function to combine data from different DataFrames into a new DataFrame. In this case, you’ll use `concat` to create a new DataFrame containing the preprocessed data. You can learn more about the `concat` function in [this section of the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html).

6. Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

    * In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

    * The rest of the DataFrame columns will become the features set `X`. 
    
7. Create the training and testing sets using the `train_test_split` function from scikit-learn.

8. Use scikit-learn’s `StandardScaler` to standardize the numerical features.

#### Create a Neural Network Model to Predict Employee Attrition

1. Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

    * Set a variable `number_input_features` equal to the number of input features.

    * Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

    * Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

    * Add the model’s layers, and use the `relu` activation function for each hidden layer.

    * This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

2. Display the structure of your model using the `summary` function.

3. Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.


#### Train and Evaluate the Neural Network Model

1. Train (fit) the neural network model. Use the training data and set 100 epochs.

2. Evaluate the model using the test data to determine its loss and accuracy.


## References:

[Keras Sequential model](https://keras.io/api/models/sequential/)

[Keras Dense module](https://keras.io/api/layers/core_layers/dense/)

[Keras evaluate](https://keras.io/api/models/model_training_apis/)

[SKLearn OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [1]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

---

## Preprocess the data.

### Step 1: Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

In [2]:
# Read the HR-Employee-Attrition.csv file from the Resources folder into a Pandas DataFrame
employee_df = pd.read_csv(Path("../Resources/HR-Employee-Attrition.csv"))

### Step 2: Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

In [3]:
# Review the DataFrame
employee_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
# Review the data types associated with the columns
employee_df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

### Step 3: Create a list of categorical variables.

In [5]:
# Create a list of categorical variables 
categorical_variables = list(employee_df.dtypes[employee_df.dtypes=="object"].index)

# Display the categorical variables list
categorical_variables

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

### Step 4: Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

In [6]:
# Imports
from sklearn.preprocessing import OneHotEncoder

In [7]:
!conda list tensorflow

# packages in environment at C:\Users\pablo\anaconda3\envs\dev:
#
# Name                    Version                   Build  Channel
tensorflow                2.16.1                   pypi_0    pypi
tensorflow-intel          2.16.1                   pypi_0    pypi
tensorflow-io-gcs-filesystem 0.31.0                   pypi_0    pypi

In [8]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse_output=False)

# Encode categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(employee_df[categorical_variables])
encoded_data

array([[0., 1., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       [0., 1., 0., ..., 1., 0., 1.],
       ...,
       [1., 0., 0., ..., 1., 0., 1.],
       [1., 0., 0., ..., 1., 1., 0.],
       [1., 0., 0., ..., 1., 1., 0.]])

In [9]:
# Create a DataFrame with the encoded variables
# The column names should match those of the encoded variables
encoded_df = pd.DataFrame(
    encoded_data, columns=enc.get_feature_names_out(categorical_variables)
)

# Display the DataFrame
encoded_df

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1466,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1467,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1468,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1469,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 5: Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

In [10]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = employee_df.drop(columns= categorical_variables)

# Review the DataFrame
numerical_variables_df

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,3,80,1,17,3,3,5,2,0,3
1466,39,613,6,1,1,2062,4,42,2,3,...,1,80,1,9,5,3,7,7,1,7
1467,27,155,4,3,1,2064,2,87,4,2,...,2,80,1,6,0,3,6,2,0,3
1468,49,1023,2,3,1,2065,4,63,2,2,...,4,80,0,17,3,2,9,6,0,8
1469,34,628,8,3,1,2068,2,82,4,2,...,1,80,0,6,3,4,4,3,1,2

In [11]:
# Using the Pandas concat function, combine the DataFrames the contain the encoded categorical data and the numerical data
attrition_df = pd.concat([numerical_variables_df, encoded_df], axis=1)

# Reveiw the DataFrame
attrition_df

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1466,39,613,6,1,1,2062,4,42,2,3,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1467,27,155,4,3,1,2064,2,87,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
1468,49,1023,2,3,1,2065,4,63,2,2,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1469,34,628,8,3,1,2068,2,82,4,2,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [12]:
# Reveiw the DataFrame
attrition_df.info()
# Reveiw the DataFrame
attrition_df.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 57 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Age                                1470 non-null   int64
 1   DailyRate                          1470 non-null   int64
 2   DistanceFromHome                   1470 non-null   int64
 3   Education                          1470 non-null   int64
 4   EmployeeCount                      1470 non-null   int64
 5   EmployeeNumber                     1470 non-null   int64
 6   EnvironmentSatisfaction            1470 non-null   int64
 7   HourlyRate                         1470 non-null   int64
 8   JobInvolvement                     1470 non-null   int64
 9   JobLevel                           1470 non-null   int64
 10  JobSatisfaction                    1470 non-null   int64
 11  MonthlyIncome                      1470 non-null   int64
 12  MonthlyRate                        1470 non-null   int64
 13  NumCompaniesWorked                 1470 non-null   int64
 14  PercentSalaryHike                  1470 non-null   int64
 15  PerformanceRating                  1470 non-null   int64
 16  RelationshipSatisfaction           1470 non-null   int64
 17  StandardHours                      1470 non-null   int64
 18  StockOptionLevel                   1470 non-null   int64
 19  TotalWorkingYears                  1470 non-null   int64
 20  TrainingTimesLastYear              1470 non-null   int64
 21  WorkLifeBalance                    1470 non-null   int64
 22  YearsAtCompany                     1470 non-null   int64
 23  YearsInCurrentRole                 1470 non-null   int64
 24  YearsSinceLastPromotion            1470 non-null   int64
 25  YearsWithCurrManager               1470 non-null   int64
 26  Attrition_No                       1470 non-null   float64
 27  Attrition_Yes                      1470 non-null   float64
 28  BusinessTravel_Non-Travel          1470 non-null   float64
 29  BusinessTravel_Travel_Frequently   1470 non-null   float64
 30  BusinessTravel_Travel_Rarely       1470 non-null   float64
 31  Department_Human Resources         1470 non-null   float64
 32  Department_Research & Development  1470 non-null   float64
 33  Department_Sales                   1470 non-null   float64
 34  EducationField_Human Resources     1470 non-null   float64
 35  EducationField_Life Sciences       1470 non-null   float64
 36  EducationField_Marketing           1470 non-null   float64
 37  EducationField_Medical             1470 non-null   float64
 38  EducationField_Other               1470 non-null   float64
 39  EducationField_Technical Degree    1470 non-null   float64
 40  Gender_Female                      1470 non-null   float64
 41  Gender_Male                        1470 non-null   float64
 42  JobRole_Healthcare Representative  1470 non-null   float64
 43  JobRole_Human Resources            1470 non-null   float64
 44  JobRole_Laboratory Technician      1470 non-null   float64
 45  JobRole_Manager                    1470 non-null   float64
 46  JobRole_Manufacturing Director     1470 non-null   float64
 47  JobRole_Research Director          1470 non-null   float64
 48  JobRole_Research Scientist         1470 non-null   float64
 49  JobRole_Sales Executive            1470 non-null   float64
 50  JobRole_Sales Representative       1470 non-null   float64
 51  MaritalStatus_Divorced             1470 non-null   float64
 52  MaritalStatus_Married              1470 non-null   float64
 53  MaritalStatus_Single               1470 non-null   float64
 54  Over18_Y                           1470 non-null   float64
 55  OverTime_No                        1470 non-null   float64
 56  OverTime_Yes                       1470 non-null   float64
dtypes: float64(31), int64(26)
memory usage: 654.7 KB

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager', 'Attrition_No',
       'Attrition_Yes', 'BusinessTravel_Non-Travel',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Human Resources',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Female', 'Gender_Male',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single', 'Over18_Y',
       'OverTime_No', 'OverTime_Yes'],
      dtype='object')

### Step 6: Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

    * In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

    * The rest of the DataFrame columns will become the features set `X`.

In [13]:
# Define the target set y using the Attrition_Yes column
y = attrition_df["Attrition_Yes"]

# Display a sample of y
y[:5]

0    1.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: Attrition_Yes, dtype: float64

In [14]:
# Define features set X by selecting all columns but Attrition_Yes and Attrition_No
X = attrition_df.drop(columns=["Attrition_Yes", "Attrition_No"])

# Review the features DataFrame
X.columns

Index(['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobSatisfaction', 'MonthlyIncome',
       'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike',
       'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'YearsWithCurrManager',
       'BusinessTravel_Non-Travel', 'BusinessTravel_Travel_Frequently',
       'BusinessTravel_Travel_Rarely', 'Department_Human Resources',
       'Department_Research & Development', 'Department_Sales',
       'EducationField_Human Resources', 'EducationField_Life Sciences',
       'EducationField_Marketing', 'EducationField_Medical',
       'EducationField_Other', 'EducationField_Technical Degree',
       'Gender_Female', 'Gender_Male', 'JobRole_Healthcare Representative',
       'JobRole_Human Resources', 'JobRole_Laboratory Technician',
       'JobRole_Manager', 'JobRole_Manufacturing Director',
       'JobRole_Research Director', 'JobRole_Research Scientist',
       'JobRole_Sales Executive', 'JobRole_Sales Representative',
       'MaritalStatus_Divorced', 'MaritalStatus_Married',
       'MaritalStatus_Single', 'Over18_Y', 'OverTime_No', 'OverTime_Yes'],
      dtype='object')

### Step 7: Create the training and testing sets using the `train_test_split` function from scikit-learn.

In [15]:
# Split the data into training and testing datasets
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

### Step 8: Use scikit-learn’s `StandardScaler` to standardize the numerical features.

In [16]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Scale both the training and testing data from the features dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Create a Neural Network Model to Predict Employee Attrition

### Step 1: Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

    * Set a variable `number_input_features` equal to the number of input features.

    * Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

    * Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

    * Add the model’s layers, and use the `relu` activation function for each hidden layer.

    * This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

In [17]:
# attrition_df.info()
len(X_train.iloc[0])

55

In [18]:
mean = (len(X_train.iloc[0]) + 1)//2

In [19]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Define the number of hidden nodes for the first hidden layer
# Use the mean of the number of input features plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer1 =  (number_input_features + 1) //2

# Define the number of hidden nodes for the second hidden layer
# Use the mean of the number of hidden nodes in the first hidden layer plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1)// 2

# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer specifying the number of inputs, the number of hidden nodes, and the activation function
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer specifying the number of hidden nodes and the activation function
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

c:\Users\pablo\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

### Step 2: Display the structure of your model using the `summary` function.

In [20]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 28)             │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14)             │           406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,989 (7.77 KB)

 Trainable params: 1,989 (7.77 KB)

 Non-trainable params: 0 (0.00 B)

### Step 3: Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.

In [21]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

---

## Train and Evaluate the Neural Network Model

### Step 1: Train (fit) the neural network model. Use the training data and set 100 epochs.

In [22]:
# Fit the model using 100 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 706us/step - accuracy: 0.7478 - loss: 0.5654
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.8284 - loss: 0.4545
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.8304 - loss: 0.4036
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 604us/step - accuracy: 0.8482 - loss: 0.3492
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.8521 - loss: 0.3372
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 0.8642 - loss: 0.3258
Epoch 7/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.8785 - loss: 0.3095
Epoch 8/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.8805 - loss: 0.3001
Epoch 9/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 584us/step - accuracy: 0.8779 - loss: 0.3165
Epoch 10/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.8804 - loss: 0.2816
Epoch 11/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9062 - loss: 0.2583
Epoch 12/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.8905 - loss: 0.2520
Epoch 13/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.8988 - loss: 0.2499
Epoch 14/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 534us/step - accuracy: 0.8950 - loss: 0.2547
Epoch 15/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9094 - loss: 0.2354
Epoch 16/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9222 - loss: 0.2315
Epoch 17/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9208 - loss: 0.2304
Epoch 18/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - accuracy: 0.9274 - loss: 0.2126
Epoch 19/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 463us/step - accuracy: 0.9137 - loss: 0.2182
Epoch 20/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step - accuracy: 0.9260 - loss: 0.2103
Epoch 21/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9216 - loss: 0.2090
Epoch 22/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9380 - loss: 0.1812
Epoch 23/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9364 - loss: 0.1776
Epoch 24/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 0.9333 - loss: 0.1816
Epoch 25/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9428 - loss: 0.1638
Epoch 26/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9337 - loss: 0.1792
Epoch 27/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.9401 - loss: 0.1772
Epoch 28/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9386 - loss: 0.1629
Epoch 29/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 477us/step - accuracy: 0.9528 - loss: 0.1561
Epoch 30/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 461us/step - accuracy: 0.9623 - loss: 0.1372
Epoch 31/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9496 - loss: 0.1654
Epoch 32/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.9579 - loss: 0.1395
Epoch 33/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9597 - loss: 0.1370
Epoch 34/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9569 - loss: 0.1279
Epoch 35/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9722 - loss: 0.1240
Epoch 36/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 466us/step - accuracy: 0.9638 - loss: 0.1295
Epoch 37/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9756 - loss: 0.1089
Epoch 38/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9737 - loss: 0.1072
Epoch 39/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9681 - loss: 0.1025
Epoch 40/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 668us/step - accuracy: 0.9725 - loss: 0.1041
Epoch 41/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 473us/step - accuracy: 0.9707 - loss: 0.0948
Epoch 42/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9694 - loss: 0.1141
Epoch 43/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 648us/step - accuracy: 0.9694 - loss: 0.1014
Epoch 44/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9744 - loss: 0.0943
Epoch 45/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.9778 - loss: 0.0894
Epoch 46/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.9806 - loss: 0.0798
Epoch 47/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9770 - loss: 0.0943
Epoch 48/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9787 - loss: 0.0835
Epoch 49/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9732 - loss: 0.0751
Epoch 50/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9769 - loss: 0.0717
Epoch 51/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.9898 - loss: 0.0615
Epoch 52/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 459us/step - accuracy: 0.9863 - loss: 0.0600
Epoch 53/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 487us/step - accuracy: 0.9859 - loss: 0.0562
Epoch 54/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 458us/step - accuracy: 0.9883 - loss: 0.0575
Epoch 55/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 605us/step - accuracy: 0.9850 - loss: 0.0608
Epoch 56/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 575us/step - accuracy: 0.9882 - loss: 0.0549
Epoch 57/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9898 - loss: 0.0468
Epoch 58/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 532us/step - accuracy: 0.9856 - loss: 0.0544
Epoch 59/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9895 - loss: 0.0489
Epoch 60/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9886 - loss: 0.0504
Epoch 61/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9914 - loss: 0.0419
Epoch 62/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9946 - loss: 0.0409
Epoch 63/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 577us/step - accuracy: 0.9896 - loss: 0.0413
Epoch 64/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.9926 - loss: 0.0408
Epoch 65/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9877 - loss: 0.0422
Epoch 66/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.9926 - loss: 0.0348
Epoch 67/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.9916 - loss: 0.0362
Epoch 68/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9956 - loss: 0.0305
Epoch 69/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 678us/step - accuracy: 0.9962 - loss: 0.0277
Epoch 70/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9907 - loss: 0.0288
Epoch 71/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9927 - loss: 0.0277
Epoch 72/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.9973 - loss: 0.0241
Epoch 73/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9961 - loss: 0.0259
Epoch 74/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9990 - loss: 0.0219
Epoch 75/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9957 - loss: 0.0228
Epoch 76/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9975 - loss: 0.0230
Epoch 77/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 0.9990 - loss: 0.0204
Epoch 78/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 516us/step - accuracy: 0.9981 - loss: 0.0212
Epoch 79/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 481us/step - accuracy: 0.9988 - loss: 0.0190
Epoch 80/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 480us/step - accuracy: 0.9977 - loss: 0.0178
Epoch 81/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 519us/step - accuracy: 0.9990 - loss: 0.0165
Epoch 82/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 531us/step - accuracy: 0.9943 - loss: 0.0205
Epoch 83/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 485us/step - accuracy: 0.9981 - loss: 0.0165
Epoch 84/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.9993 - loss: 0.0138
Epoch 85/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 620us/step - accuracy: 0.9990 - loss: 0.0154
Epoch 86/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 1.0000 - loss: 0.0131
Epoch 87/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 1.0000 - loss: 0.0136
Epoch 88/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 457us/step - accuracy: 1.0000 - loss: 0.0122
Epoch 89/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 633us/step - accuracy: 1.0000 - loss: 0.0106
Epoch 90/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 1.0000 - loss: 0.0101
Epoch 91/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 1.0000 - loss: 0.0095
Epoch 92/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 1.0000 - loss: 0.0089
Epoch 93/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 488us/step - accuracy: 1.0000 - loss: 0.0099
Epoch 94/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 1.0000 - loss: 0.0081
Epoch 95/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 1.0000 - loss: 0.0076
Epoch 96/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 504us/step - accuracy: 1.0000 - loss: 0.0084
Epoch 97/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 1.0000 - loss: 0.0084
Epoch 98/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 1.0000 - loss: 0.0079
Epoch 99/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 1.0000 - loss: 0.0068
Epoch 100/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 1.0000 - loss: 0.0074

### Step 2: Evaluate the model using the test data to determine its loss and accuracy.

In [23]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled, y_test, verbose=0)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Loss: 0.7979080080986023, Accuracy: 0.85597825050354

### Step 3: Save and export your model to an HDF5 file. Name the file `employee_attrition.h5`.

In [26]:
# Set the model's file path
file_path = Path("../Resources/employee_attrition.h5")

# Export your model to a HDF5 fil
nn.save(file_path)

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.