# Predicting Employees Attrition

In this activity, you will apply your knowledge of deep learning models to predict whether an employee is likely to depart from a company.

## Instructions:

The steps for this activity are broken out into the following sections:

* Preprocess the data.

* Create a neural network model to predict employee attrition.

* Train and evaluate the neural network model.


#### Preprocess the Data 

1. Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

2. Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

3. Create a list of categorical variables.

> **Rewind** The Pandas DataFrame `dtypes` property returns a Pandas Series that displays the data type of each column. The column name is the index. You can create the list of categorical variables manually. Or, you can use Pandas filtering. For more detail about the filtering process, review the [`dtypes` documentation at Pandas API reference](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dtypes.html).

4. Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

5. Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

> **Note** To complete this step, you will employ the Pandas `concat()` function, which was introduced earlier in the course. Recall that we use the `concat` function to combine data from different DataFrames into a new DataFrame. In this case, you’ll use `concat` to create a new DataFrame containing the preprocessed data. You can learn more about the `concat` function in [this section of the Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html).

6. Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

    * In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

    * The rest of the DataFrame columns will become the features set `X`. 
    
7. Create the training and testing sets using the `train_test_split` function from scikit-learn.

8. Use scikit-learn’s `StandardScaler` to standardize the numerical features.

#### Create a Neural Network Model to Predict Employee Attrition

1. Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

    * Set a variable `number_input_features` equal to the number of input features.

    * Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

    * Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

    * Add the model’s layers, and use the `relu` activation function for each hidden layer.

    * This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

2. Display the structure of your model using the `summary` function.

3. Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.


#### Train and Evaluate the Neural Network Model

1. Train (fit) the neural network model. Use the training data and set 100 epochs.

2. Evaluate the model using the test data to determine its loss and accuracy.


## References:

[Keras Sequential model](https://keras.io/api/models/sequential/)

[Keras Dense module](https://keras.io/api/layers/core_layers/dense/)

[Keras evaluate](https://keras.io/api/models/model_training_apis/)

[SKLearn OneHotEncoder](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [9]:
# Imports
import pandas as pd
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

---

## Preprocess the data.

### Step 1: Read the `HR-Employee-Attrition.csv` file from the Resources folder and create a DataFrame.

In [10]:
# Read the HR-Employee-Attrition.csv file from the Resources folder into a Pandas DataFrame
employee_df = pd.read_csv(
    Path("../Resources/HR-Employee-Attrition.csv")
)

### Step 2: Review the resulting DataFrame. Check the data type associated with each column to identify categorical and non-categorical variables.

> **Hint** Recall that categorical variables have an `object` data type.

In [11]:
# Review the DataFrame
employee_df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [12]:
# Review the data types associated with the columns
employee_df.dtypes

Age                          int64
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

### Step 3: Create a list of categorical variables.

In [13]:
# Create a list of categorical variables 
categorical_variables = list(employee_df.dtypes[employee_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

### Step 4: Use the `OneHotEncoder` module from scikit-learn to encode the data set's categorical variables.

In [14]:
# Imports
from sklearn.preprocessing import OneHotEncoder

In [15]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

# Encode categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(employee_df[categorical_variables])

c:\Users\pablo\anaconda3\envs\dev\lib\site-packages\sklearn\preprocessing\_encoders.py:972: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [17]:
# Create a DataFrame with the encoded variables
# The column names should match those of the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Display the DataFrame
encoded_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 5: Create a new DataFrame named `attrition_df` that contains the encoded categorical variables and the numerical variables from the original dataset.

In [18]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = employee_df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1102,1,2,1,1,2,94,3,2,...,1,80,0,8,0,1,6,4,0,5
1,49,279,8,1,1,2,3,61,2,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1373,2,2,1,4,4,92,2,1,...,2,80,0,7,3,3,0,0,0,0
3,33,1392,3,4,1,5,4,56,3,1,...,3,80,0,8,3,3,8,7,3,0
4,27,591,2,1,1,7,1,40,3,1,...,4,80,1,6,3,3,2,2,2,2

In [19]:
# Using the Pandas concat function, combine the DataFrames the contain the encoded categorical data and the numerical data
attition_df = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)

# Reveiw the DataFrame
attition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 6: Use `attrition_df` to create the features (`X`) and target (`y`) sets. 

    * In this activity, we want to build a model that predicts whether a person is at risk for attrition. So, we must separate the attrition columns from the rest of the input data. In fact, because the attrition data is binary (one of two values), we only need to keep the “Attrition_Yes” column. We can ignore the “Attrition_No” column, because it is redundant. So, the “Attrition_Yes” column will become the target set `y`.

    * The rest of the DataFrame columns will become the features set `X`.

In [20]:
# Define the target set y using the Attrition_Yes column
y = attition_df["Attrition_Yes"]

# Display a sample of y
y[:5]

0    1.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: Attrition_Yes, dtype: float64

In [21]:
# Define features set X by selecting all columns but Attrition_Yes and Attrition_No
X = attition_df.drop(columns=["Attrition_Yes", "Attrition_No"])

# Review the features DataFrame
X.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

### Step 7: Create the training and testing sets using the `train_test_split` function from scikit-learn.

In [22]:
# Split the data into training and testing datasets
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 8: Use scikit-learn’s `StandardScaler` to standardize the numerical features.

In [23]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Create a Neural Network Model to Predict Employee Attrition

### Step 1: Use the optimization techniques presented in this lesson to create a deep neural network model with two hidden layers.

    * Set a variable `number_input_features` equal to the number of input features.

    * Set a variable `hidden_nodes_layer1` equal to an integer number close to the mean of the number of input features and the number of neurons in the output layer.

    * Set a variable `hidden_nodes_layer2` equal to an integer number close to the mean of the number of hidden nodes defined for the first layer and the number of neurons in the output layer.

    * Add the model’s layers, and use the `relu` activation function for each hidden layer.

    * This model will predict a binary output. So, add an output layer with one neuron, and use the `sigmoid` activation function.

> **Hint** To set the number of input features, you can fetch the length of the first element, like this: `number_input_features = len(X_train.iloc[0])`.

In [24]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Define the number of hidden nodes for the first hidden layer
# Use the mean of the number of input features plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Define the number of hidden nodes for the second hidden layer
# Use the mean of the number of hidden nodes in the first hidden layer plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer specifying the number of inputs, the number of hidden nodes, and the activation function
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer specifying the number of hidden nodes and the activation function
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

c:\Users\pablo\anaconda3\envs\dev\lib\site-packages\keras\src\layers\core\dense.py:85: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

### Step 2: Display the structure of your model using the `summary` function.

In [25]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 28)             │         1,568 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 14)             │           406 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,989 (7.77 KB)

 Trainable params: 1,989 (7.77 KB)

 Non-trainable params: 0 (0.00 B)

### Step 3: Compile the model. Use the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` metric.

In [26]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

---

## Train and Evaluate the Neural Network Model

### Step 1: Train (fit) the neural network model. Use the training data and set 100 epochs.

In [27]:
# Fit the model using 100 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 1s 691us/step - accuracy: 0.7722 - loss: 0.5828
Epoch 2/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 517us/step - accuracy: 0.8628 - loss: 0.4138
Epoch 3/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.8461 - loss: 0.3841
Epoch 4/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.8543 - loss: 0.3463
Epoch 5/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 500us/step - accuracy: 0.8496 - loss: 0.3350
Epoch 6/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.8679 - loss: 0.3021
Epoch 7/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.8831 - loss: 0.3022
Epoch 8/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9072 - loss: 0.2563
Epoch 9/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.8845 - loss: 0.2957
Epoch 10/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9127 - loss: 0.2530
Epoch 11/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 576us/step - accuracy: 0.9000 - loss: 0.2520
Epoch 12/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9230 - loss: 0.2157
Epoch 13/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9150 - loss: 0.2345
Epoch 14/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 559us/step - accuracy: 0.9251 - loss: 0.2161
Epoch 15/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 474us/step - accuracy: 0.9292 - loss: 0.1978
Epoch 16/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9385 - loss: 0.1867
Epoch 17/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9226 - loss: 0.2122
Epoch 18/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9300 - loss: 0.1870
Epoch 19/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9341 - loss: 0.1657
Epoch 20/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9344 - loss: 0.1825
Epoch 21/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9389 - loss: 0.1763
Epoch 22/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9365 - loss: 0.1685
Epoch 23/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9346 - loss: 0.1680
Epoch 24/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9411 - loss: 0.1562
Epoch 25/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9364 - loss: 0.1541
Epoch 26/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9392 - loss: 0.1482
Epoch 27/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9438 - loss: 0.1340
Epoch 28/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9519 - loss: 0.1207
Epoch 29/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9622 - loss: 0.1205
Epoch 30/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9567 - loss: 0.1077
Epoch 31/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9611 - loss: 0.1191
Epoch 32/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.9689 - loss: 0.0985
Epoch 33/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 543us/step - accuracy: 0.9748 - loss: 0.0956
Epoch 34/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9795 - loss: 0.0905
Epoch 35/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9766 - loss: 0.0894
Epoch 36/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9812 - loss: 0.0837
Epoch 37/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9845 - loss: 0.0769
Epoch 38/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 0.9892 - loss: 0.0670
Epoch 39/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.9877 - loss: 0.0684
Epoch 40/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9892 - loss: 0.0653
Epoch 41/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9938 - loss: 0.0603
Epoch 42/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9887 - loss: 0.0589
Epoch 43/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9912 - loss: 0.0554
Epoch 44/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9909 - loss: 0.0523
Epoch 45/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9925 - loss: 0.0517
Epoch 46/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9908 - loss: 0.0482
Epoch 47/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9966 - loss: 0.0406
Epoch 48/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9963 - loss: 0.0402
Epoch 49/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9958 - loss: 0.0329
Epoch 50/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9979 - loss: 0.0358
Epoch 51/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9980 - loss: 0.0328
Epoch 52/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9949 - loss: 0.0340
Epoch 53/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.9991 - loss: 0.0289
Epoch 54/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.9964 - loss: 0.0286
Epoch 55/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9979 - loss: 0.0250
Epoch 56/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9941 - loss: 0.0260
Epoch 57/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9952 - loss: 0.0269
Epoch 58/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9986 - loss: 0.0206
Epoch 59/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9983 - loss: 0.0215
Epoch 60/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.9965 - loss: 0.0212
Epoch 61/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.9988 - loss: 0.0185
Epoch 62/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9991 - loss: 0.0167
Epoch 63/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9985 - loss: 0.0155
Epoch 64/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9975 - loss: 0.0176
Epoch 65/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9983 - loss: 0.0168
Epoch 66/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9993 - loss: 0.0172
Epoch 67/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 751us/step - accuracy: 0.9998 - loss: 0.0139
Epoch 68/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9973 - loss: 0.0138
Epoch 69/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9989 - loss: 0.0109
Epoch 70/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9978 - loss: 0.0131
Epoch 71/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9994 - loss: 0.0099
Epoch 72/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9963 - loss: 0.0125
Epoch 73/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 580us/step - accuracy: 0.9989 - loss: 0.0099
Epoch 74/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9985 - loss: 0.0094
Epoch 75/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 0.9979 - loss: 0.0098
Epoch 76/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9988 - loss: 0.0081
Epoch 77/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 0.9989 - loss: 0.0076
Epoch 78/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 0.9989 - loss: 0.0079
Epoch 79/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 544us/step - accuracy: 0.9994 - loss: 0.0074
Epoch 80/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 536us/step - accuracy: 0.9982 - loss: 0.0075
Epoch 81/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 0.9994 - loss: 0.0072
Epoch 82/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 0.9995 - loss: 0.0072
Epoch 83/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 0.9998 - loss: 0.0057
Epoch 84/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 1.0000 - loss: 0.0067
Epoch 85/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 561us/step - accuracy: 1.0000 - loss: 0.0058
Epoch 86/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 589us/step - accuracy: 1.0000 - loss: 0.0053
Epoch 87/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 574us/step - accuracy: 1.0000 - loss: 0.0082
Epoch 88/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 560us/step - accuracy: 0.9997 - loss: 0.0047
Epoch 89/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 1.0000 - loss: 0.0047
Epoch 90/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 546us/step - accuracy: 1.0000 - loss: 0.0041
Epoch 91/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 530us/step - accuracy: 1.0000 - loss: 0.0051
Epoch 92/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 562us/step - accuracy: 1.0000 - loss: 0.0051
Epoch 93/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 545us/step - accuracy: 1.0000 - loss: 0.0059
Epoch 94/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 655us/step - accuracy: 1.0000 - loss: 0.0049
Epoch 95/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 650us/step - accuracy: 0.9985 - loss: 0.0050
Epoch 96/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 649us/step - accuracy: 1.0000 - loss: 0.0035
Epoch 97/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 464us/step - accuracy: 1.0000 - loss: 0.0053
Epoch 98/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 1.0000 - loss: 0.0049
Epoch 99/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 515us/step - accuracy: 1.0000 - loss: 0.0054
Epoch 100/100
35/35 ━━━━━━━━━━━━━━━━━━━━ 0s 471us/step - accuracy: 1.0000 - loss: 0.0029

### Step 2: Evaluate the model using the test data to determine its loss and accuracy.

In [28]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

12/12 - 0s - 6ms/step - accuracy: 0.8315 - loss: 1.1338
Loss: 1.1337943077087402, Accuracy: 0.83152174949646

: